export const FILL_INPUT_ERRORS = 'FILL_INPUT_ERRORS';
export const FLUSH_INPUT_ERRORS = 'FLUSH_INPUT_ERRORS';
export const FILL_INTERNAL_ERRORS = 'FILL_INTERNAL_ERRORS';
export const FLUSH_INTERNAL_ERRORS = 'FLUSH_INTERNAL_ERRORS';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const MODAL_FLUSH = 'MODAL_FLUSH';

export const POSTS_FETCH_START = 'POSTS_FETCH_START';
export const POSTS_FETCH_DONE = 'POSTS_FETCH_DONE';

export const POST_SUBMIT_START = 'POST_SUBMIT_START';
export const POST_SUBMIT_DONE = 'POST_SUBMIT_DONE';
export const POST_SUBMIT_MSG_REVERT = 'POST_SUBMIT_MSG_REVERT';
